### ISSUE TITLE
Install GENTRL Error: Can't find suitable distribution (torch == 1.0.1)  

### ISSUE THREAD

**Issue by Jiang-Lu-CAS** [insilicomedicine/GENTRL#2]
Dear Sir,
     I'm trying to install the GENTRL model, however, there was an error when I typed "python setup.py install". 
![无标题](https://user-images.githubusercontent.com/44989100/64918553-8c645380-d7d2-11e9-9c5b-2967c5db9791.png)
    As it's suggested, I search the website "https://pypi.org/simple/torch/"
and found several torch == 1.0.1, but it looks like that only can be used in Linux or Mac. Is that right? If so , how could I solve it since I'm installing this in Win10.
![2の](https://user-images.githubusercontent.com/44989100/64918584-e107ce80-d7d2-11e9-8793-99f1b40a84ad.png)
   Hoping for your early reply.
   Best,
Jane

**Comment by danpol** [comment]
PyTorch 1.0.1 is only supported on Linux and Mac.
