### ISSUE TITLE
download dataset_v1.csv

### ISSUE THREAD

**Issue by cgh2797** [insilicomedicine/GENTRL#21]
I am a Windows user, but there is no wget in Windows.

so I install it and download it with wget, but it cannot be download. 

Can you send me another method or dataset_v1.csv file?

----------error message-----------------------------------------------------
https://media.githubusercontent.com/media/molecularsets/moses/master/data/dataset_v1.csv
           => dataset_v1.csv
Resolving media.githubusercontent.com... 151.101.228.133
Connecting to media.githubusercontent.com|151.101.228.133|:443... connected.
ERROR: Certificate verification error for media.githubusercontent.com: unable to get local issuer certificate
ERROR: certificate common name www.github.com doesn't match requested host name media.githubusercontent.com.
To connect to media.githubusercontent.com insecurely, use --no-check-certificate.
Unable to establish SSL connection.

**Comment by danpol** [comment]
`wget` is a program for downloading files. You can download the file directly from the link in issue description (https://media.githubusercontent.com/media/molecularsets/moses/master/data/dataset_v1.csv)
