### ISSUE TITLE
How long will cost for pretraning

### ISSUE THREAD

**Issue by Flyfoxs** [insilicomedicine/GENTRL#4]
I have enough GPU(20G+), but pretraning only cost 4G+. And more thant 10 hours is gone, still no model generated, and app is still running.

**Comment by Jiang-Lu-CAS** [comment]
I also ran it more than 10 hours, but it broken down. How about yours?

![2](https://user-images.githubusercontent.com/44989100/65306228-7fbb7300-dbb7-11e9-875d-334066c71ddd.png)

**Comment by danpol** [comment]
@Jiang-Lu-CAS, On your screenshot, the model finished training successfully. Next cells save the model to `saved_gentrl` directory. You should run `train_rl.ipynb` next, as explicitly said in `README.md`

**Comment by danpol** [comment]
@Flyfoxs, pretraining takes around 30 hours, depending on the hardware specifications

**Comment by Flyfoxs** [comment]
@danpol 
thanks, after the pretraning,  How long will cost for the traning
