### ISSUE TITLE
What can I do after training the model (VAE and RL)?

### ISSUE THREAD

**Issue by dakoner** [insilicomedicine/GENTRL#6]
Hi,
I have successfully completed both steps of training.  It's not clear what the next steps are.  I am familiar with previous autoenc/dec models, so I want to (for example), take two SMILES strings, draw a vector between them in encoded space, and decode valid SMILES strings along their interpolation, or, explore around a starting SMILES strings. 

If you explain, I can write up some example and send a PR.

**Comment by dakoner** [comment]
I missed that there is already a notebook called 'examples/sample.ipynb' that does this.

**Comment by xuzhang5788** [comment]
@dakoner 
I ran sample.ipynb after I successfully completed both steps of training, but I got 100 same molecules. I am not sure if my training or RL have problems.

**Comment by dakoner** [comment]
There's a couple bug in the script, I will send a PR.  I

**Comment by xuzhang5788** [comment]
@dakoner 
Did you know if the bugs have been fixed? Many thanks

**Comment by Bibyutatsu** [comment]
Hi xuzhang5788,
If everything is correct and you are sampling correctly then I think this mainly happens when your RL step is overfitted. Please try with less number of `num_iterations`.
